name: Build ESP (.tipa)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Build
        run: |
          make package

      - name: Upload .tipa
        uses: actions/upload-artifact@v4
        with:
          name: ESP-tipa
          path: packages/*.tipa
